export const poemIntergalite = [
  ["Tu souhaites l'intèrgalité"],
  [
    "Et un jours tu seras pourquoi pas le français",
    "Si tu veux tous les temps va falloir se laver",
    "Assez tôt c'est vraiment un job de déterré",
    "Tous les camps dans un car et tu dois tout rogner",
    "Il est désormais tard rien ne rouille dans mon bad",
    "Gorgée de cette coupe là, ne tient pas dans un tort",
    "Une ration hors la loie, rien qui vaille le mentor",
    "tu le veux toi aussi, l'intégralité ?",
    "Je t'en prie rejoins moi, viens dont la trouver",
    "Qu'on soit deux c'est sympa, entre c'est pareil",
    "A quel point tu capte pas, c'est plus mon terminal",
    "Moi je jongle dans la funk, pointes innéquilibrées",
    "Si j'y reste je m'y noie, piquante vérité",
    "Rétrécir je le crois, vous n'êtes pas des aïnés",
    "Ni mes frères je m'en bat, tu sais se que tu foie",
    "Viens dont retrouve moi, dans ces opales salées",
  ],
  [
    "Je le jure conviendra, on peux les respecter",
    "Les paroles font le toit; un peu moins aiguisé",
    "Je l'assure comme tiendra, on peux le présager",
    "Les narines font la loi; un peu moins classifiée",
    "Je l'assume je vois pas, je peux juste m'enfiler",
    "Les latrines font la soie; un peu moins décalée",
    "Corps perdu temps pressé, je m'suis fait envrillé",
    "Rendez vous au croisième, le paradis bocale",
    "Feignant le barde inné, et la parbapapote",
    "Qui te tôme sous le nez, au moment de la barre",
    "Tante de la relever, en mattant ta dernière",
    "Tu verras l'excitant; la réponse avariée",
    "tu le veux toi aussi, l'eugène fou allier",
    "Je t'en prie réjouis moi, viens dont le prouver",
    "Non ne gagne du temps, à venir m'épiler",
    "Après rien tout les tants, et j'essaye d'avancer",
    "Yoga le reluisant, leste dans nos pensées",
    "Et puis plus rien",
  ],
];
