export const breves: string[][] = [
  [
    "My small channel I love, all begins with the Saints",
    "don't you know the story where you may learn and see",
    "how best men can ignore what's in front of their sight",
    "the fortunate of you will enjoy probably",
    "the abridged version is a way nicer flight",
  ],
  [
    "I've lost my balls somewhere in dishes",
    "It smells like fish in my blue underwear",
    "Go find them all to fullfill your wishes",
    "You'll see the Dragon flying in the air",
  ],
  [
    "My small channel I love, all begins with the Saints",
    "don't you know the story where you may learn and see",
    "how best men can ignore what's in front of their sight",
    "the fortunate of you will enjoy probably",
    "the abridged version is a way nicer flight",
  ],
  [
    "A cheap yellow cheese that runs everywhere",
    "trambling the flesh of my whole body",
    "Trop fort pour moi, obligé de me taire",
    "This is how the bacon is supposed to be",
    "Even though not the one I prefer",
    "I'll always love you my burger familly",
  ],
  [
    "I jabed this seed to grow stronger beats",
    "Making my people feel a unique Accord",
    "Many tears lost for the one I pick",
    "A warrior should know the lyrics of his Lord",
  ],

  [
    "My manhood in a cage to be your husband",
    "The best of the beast but you refused me",
    "I can't kill a bear alone with my hand",
    "And I only have one single body",
    "I'll be a good boy to kiss your sweet land",
  ],
  [
    "How fighting a man, no body but gum",
    "No definition, or maybe just strong",
    "Absorbing the best, allways changing of form",
    "Let's try vibrations, genkidama song",
  ],
  [
    "Tasukete Tasukete master of the beasts",
    "I may be a flack, contained in a cage",
    "Go fight for our sake great illusionist",
    "We're taking your back, we just need courage",
    "The one thing you lack, to know the defeat",
    "Send chicken attacks in the street of rage",
  ],
  [
    "Qu'ai-je fais au bon dieu mon aînée",
    "pour Qui le mirroir se maquille",
    "L'aurais-je élevé comme une traînée ?",
    "La vie est un long fleuve tranquille",
  ],
  [
    "A boy with a dream is my mission to Mars",
    "A head in the sky inline to rule them all",
    "No need any fuel to propel my cars",
    "My pal you'll pay to soften the downfall",
    "I'll touch the heart of the nation of stars",
    "My loving story lies in freedom and balls",
  ],
];
